### ISSUE TITLE
Crash on startup if remote repo.json contains invalid JSON

### ISSUE THREAD

**Issue by chromakode** [chromakode/signet#6]
```
Traceback (most recent call last):
  File "./sig", line 875, in <module>
    SigCLI().run()
  File "./sig", line 687, in run
    self.sig.load(os.environ.get('SIG_DIR'))
  File "./sig", line 437, in load
    remote_repo.load()
  File "./sig", line 281, in load
    attestation = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
```

**Comment by chromakode** [comment]
Fixed in 36f247c1087ac5b6a94b41e834b05aa9223cfc65
